# Generated by Django 3.2.7 on 2021-10-27 03:50

import analises.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to=analises.models.file_path)),
                ('name', models.CharField(max_length=50)),
                ('resume', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
