# Generated by Django 3.2.7 on 2021-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehandler',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
