# Generated by Django 3.1.7 on 2021-09-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Customer Email'),
        ),
    ]
