# Generated by Django 3.2.7 on 2021-10-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210920_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Image',
            field=models.ImageField(blank='True', null='True', upload_to='upload/'),
            preserve_default='True',
        ),
    ]
