# Generated by Django 3.2.7 on 2021-10-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Image',
            new_name='Image_pic',
        ),
    ]
