# Generated by Django 3.1.7 on 2021-05-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_aprender_view_assinaturas_view_home_view_login_view_noticias_view_sobre_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aprender_view',
        ),
        migrations.DeleteModel(
            name='assinaturas_view',
        ),
        migrations.DeleteModel(
            name='login_view',
        ),
        migrations.DeleteModel(
            name='noticias_view',
        ),
        migrations.DeleteModel(
            name='sobre_view',
        ),
    ]
