# Generated by Django 3.1.7 on 2021-05-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_auto_20210528_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_view',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
