# Generated by Django 3.1.7 on 2021-05-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0008_auto_20210528_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostQuemSomos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailCapa', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_capa', models.TextField()),
                ('DescrilcaoMerlin', models.TextField()),
                ('thumbnailQuemSomos', models.ImageField(blank=True, null=True, upload_to='')),
                ('DescricaoQuemSomos', models.TextField()),
                ('thumbnaiImageA', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_titleA', models.TextField()),
                ('thumbnaiImageB', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_titleB', models.TextField()),
                ('thumbnaiImageC', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_titleC', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField()),
            ],
        ),
    ]
