# Generated by Django 3.1.7 on 2021-05-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0010_postnoticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostNoticias',
        ),
    ]
