# Generated by Django 3.1.7 on 2021-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_delete_postnoticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNoticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailCarrossel1', models.ImageField(blank=True, null=True, upload_to='')),
                ('title1', models.TextField()),
                ('text1', models.TextField()),
                ('thumbnailCarrossel2', models.ImageField(blank=True, null=True, upload_to='')),
                ('title2', models.TextField()),
                ('text2', models.TextField()),
                ('thumbnailCarrossel3', models.ImageField(blank=True, null=True, upload_to='')),
                ('title3', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
    ]
