# Generated by Django 3.1.7 on 2021-05-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0012_postnoticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostNoticias',
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='thumbnailCarrossel1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='thumbnailCarrossel2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='thumbnailCarrossel3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='title1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='title2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postquemsomos',
            name='title3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
