# Generated by Django 3.1.7 on 2021-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0013_auto_20210528_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNoticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnailCarrossel1', models.ImageField(blank=True, null=True, upload_to='')),
                ('title1', models.TextField()),
                ('text1', models.TextField()),
                ('thumbnailCarrossel2', models.ImageField(blank=True, null=True, upload_to='')),
                ('title2', models.TextField()),
                ('text2', models.TextField()),
                ('thumbnailCarrossel3', models.ImageField(blank=True, null=True, upload_to='')),
                ('title3', models.TextField()),
                ('text3', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='thumbnailCarrossel1',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='thumbnailCarrossel2',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='thumbnailCarrossel3',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='postquemsomos',
            name='title3',
        ),
    ]
