# Generated by Django 3.1.7 on 2021-05-28 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0014_auto_20210528_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='postnoticias',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postnoticias',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='comentario',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='paragraphy1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='paragraphy2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='text_nosso_time',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text3',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='DescricaoQuemSomos',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='DescrilcaoMerlin',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_capa',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleA',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleB',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleC',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
