# Generated by Django 3.1.7 on 2021-05-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0015_auto_20210528_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthome',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='paragraphy1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='paragraphy2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posthome',
            name='text_nosso_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postnoticias',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='DescricaoQuemSomos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='DescrilcaoMerlin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_capa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleA',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postquemsomos',
            name='text_titleC',
            field=models.TextField(blank=True, null=True),
        ),
    ]
