# Generated by Django 3.1.7 on 2021-05-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0017_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Histórico de Visitas'},
        ),
    ]
