# Generated by Django 3.1.7 on 2021-05-30 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0018_auto_20210529_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
