# Generated by Django 3.1.7 on 2021-06-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0019_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard_home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_header', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_header', models.TextField()),
                ('link_header', models.TextField()),
                ('noticias_hoje', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_noticias_hoje', models.TextField()),
                ('bolsa_hoje', models.ImageField(blank=True, null=True, upload_to='')),
                ('link_bolsa_hoje', models.TextField()),
            ],
        ),
    ]
