# Generated by Django 3.1.7 on 2021-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0021_dashboard_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard_home',
            name='published',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard_videos',
            name='published',
            field=models.BooleanField(null=True),
        ),
    ]
