# Generated by Django 3.2.7 on 2021-10-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0022_auto_20210625_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguem',
            name='profile_image',
            field=models.ImageField(upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='bolsa_hoje',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='noticias_hoje',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='dashboard_videos',
            name='image_capa',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
