# Generated by Django 3.2.7 on 2021-10-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0023_auto_20211022_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alguem',
            name='profile_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='bolsa_hoje',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='image_header',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dashboard_home',
            name='noticias_hoje',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dashboard_videos',
            name='image_capa',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
