# Generated by Django 3.1.7 on 2021-06-25 22:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='assunto'),
        ),
    ]
