# Generated by Django 3.1.7 on 2021-06-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0002_auto_20210625_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='slug',
            new_name='slugfield',
        ),
    ]
