# Generated by Django 3.1.7 on 2021-06-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('especialista', '0003_auto_20210625_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='slugfield',
            new_name='slug',
        ),
    ]
