# Generated by Django 3.2.7 on 2021-10-23 18:57

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ReleasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('image_url', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField()),
                ('categories', models.ManyToManyField(to='release.ReleaseCategory')),
            ],
        ),
    ]
