# Generated by Django 3.2.7 on 2021-10-23 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasepost',
            name='overview',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
