# Generated by Django 3.1.7 on 2021-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Noticias_summary', models.CharField(max_length=255)),
                ('Noticias_image', models.ImageField(upload_to='')),
                ('Cursos_summary', models.CharField(max_length=255)),
                ('Cursos_image', models.ImageField(upload_to='')),
                ('Bolsa_summary', models.CharField(max_length=255)),
                ('Bolsa_image', models.ImageField(upload_to='')),
                ('Video_summary', models.CharField(max_length=255)),
                ('Video_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
