# Generated by Django 3.1.7 on 2022-01-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockVisualizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
