# Generated by Django 3.1.7 on 2021-05-30 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Histórico de Visualizações', 'verbose_name_plural': 'Histórico de Visualizações'},
        ),
    ]
