# Generated by Django 3.1.7 on 2021-05-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20210514_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
