# Generated by Django 3.2.7 on 2021-11-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20210519_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
