# Generated by Django 3.2.7 on 2021-11-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_auto_20211118_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_paid',
            field=models.BooleanField(default=False, verbose_name='Payment Status'),
        ),
    ]
