# Generated by Django 3.1.7 on 2021-05-26 18:49

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpost',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=False, editable=False, populate_from='title'),
        ),
    ]
