# Generated by Django 3.1.7 on 2021-05-28 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
