# Generated by Django 3.2.7 on 2021-10-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0012_auto_20210528_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
