# Generated by Django 3.2.7 on 2021-11-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_noticias', '0013_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
