# Generated by Django 3.1.7 on 2021-04-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_professional1', models.ImageField(upload_to='')),
                ('nome_professional1', models.CharField(max_length=255)),
                ('cargo_professional1', models.CharField(max_length=255)),
                ('image_professional2', models.ImageField(upload_to='')),
                ('nome_professional2', models.CharField(max_length=255)),
                ('cargo_professional2', models.CharField(max_length=255)),
                ('image_professional3', models.ImageField(upload_to='')),
                ('nome_professional3', models.CharField(max_length=255)),
                ('cargo_professional3', models.CharField(max_length=255)),
            ],
        ),
    ]
