# Generated by Django 3.1.7 on 2021-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinaturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_curso', models.ImageField(upload_to='')),
                ('titulo_curso', models.CharField(max_length=255)),
                ('professor_curso', models.CharField(max_length=255)),
                ('preco_curso', models.CharField(max_length=255)),
                ('parcela_curso', models.CharField(max_length=255)),
                ('imagem_ebook', models.ImageField(upload_to='')),
            ],
        ),
    ]
