# Generated by Django 3.1.7 on 2021-05-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20210530_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post_Assinaturas',
        ),
    ]
