# Generated by Django 3.1.7 on 2021-05-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20210530_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_assinaturas',
            old_name='post',
            new_name='apost',
        ),
    ]
