# Generated by Django 3.1.7 on 2021-05-31 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20210531_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_assinaturas',
            old_name='slugf',
            new_name='slug',
        ),
    ]
