# Generated by Django 3.1.7 on 2021-06-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_auto_20210531_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_assinaturas',
            old_name='slugfield',
            new_name='slug',
        ),
    ]
