# Generated by Django 3.1.7 on 2021-06-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_auto_20210531_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('preco', models.CharField(max_length=200)),
                ('parcela', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
