# Generated by Django 3.1.7 on 2021-06-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0011_cursos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['data']},
        ),
    ]
