# Generated by Django 3.1.7 on 2021-06-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0012_auto_20210602_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_assinaturas',
            old_name='thumbnails',
            new_name='images',
        ),
    ]
