# Generated by Django 3.1.7 on 2021-06-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_auto_20210604_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_assinaturas',
            name='preco',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
