# Generated by Django 3.2.7 on 2021-10-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0016_alter_author_assinaturas_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_assinaturas',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
